apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-dhmdhqal
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-dhmdhqal:bb8283bc245c780823320e1a45b25f4822421584@sha256:39694210a8826d3a6d36322bfdd67cc15e6cdb6623088bb839aac16357eccea3
          name: container-image
